### ISSUE TITLE
[Resident Evil 2 Remake] crashing after the first cutscene

### ISSUE THREAD

**Issue by bkdwt** [doitsujin/dxvk#1147]
So, I have a little problem here with RE2. This game crash every time after the first cutscene. Others games work like a charm on my system. I really don't know what is causing this.

**Software information**
-Game: Resident Evil 2 Remake
-OS: Solus Gnome 4.0
-Settings used: 1440P and 1080P with medium settings

**System information**
- GPU: RX 570 4GB
- Driver: MESA 19.0.6
- Wine version: 4.12
- DXVK version: 1.3.1

**Log files**
- d3d11.log: [re2_d3d11.log](https://gist.github.com/bkdwt/0c1f4f01b62fc821f17b301db530f1d8)
- dxgi.log: [dxgi.log:](https://gist.github.com/bkdwt/b928ae0f09134d63633aaa32e562735f)

**Comment by Joshua-Ashton** [comment]
I'm a bit confused by your dxgi.log, it seems like it's running with wined3d there?

> 002f:fixme:d3d11:d3d11_device_CheckFeatureSupport Returning fake threading support data.
> 002f:fixme:d3d11:d3d11_device_CreateDeferredContext iface 000000005C45A0F0, flags 0, context 0000000024C002D0 stub!

Might be worth trying with DXVK's DXGI.

**Comment by doitsujin** [comment]
This is not a DXVK bug. You need to set up mfplat to run the game, see https://github.com/ValveSoftware/Proton/issues/2266.

**Comment by bkdwt** [comment]
> This is not a DXVK bug. You need to set up mfplat to run the game, see [ValveSoftware/Proton#2266](https://github.com/ValveSoftware/Proton/issues/2266).
Well, this doesn't works for me. You can close this issue. ;)

**Comment by ahmed-elsayed2017** [comment]
> > This is not a DXVK bug. You need to set up mfplat to run the game, see [ValveSoftware/Proton#2266](https://github.com/ValveSoftware/Proton/issues/2266).
> 
> Well, this doesn't works for me. You can close this issue. ;)

For me some cutscenes work, and some don't work. You need to press `esc` then `space` as fast as possible before the cut-scene start to skip it.

**Comment by Majstor** [comment]
Hi,

Same issue here. The introduction runs very well (level graphics high) and at the end, infinite loading starts.
Trying the "mfplat" solution but the installcab.py seems doesn't work very well see here :
```
./install-mf-64.sh 
mediafoundation
- amd64_microsoft-windows-mediafoundation_31bf3856ad364e35_6.1.7601.17514_none_fa8534ab236134c4.manifest (win64)
- wow64_microsoft-windows-mediafoundation_31bf3856ad364e35_6.1.7601.17514_none_04d9defd57c1f6bf.manifest (wow64)
- mf.dll -> /home/majstor/.steam/steam/steamapps/compatdata/883710/pfx/drive_c/windows/system32
- mfps.dll -> /home/majstor/.steam/steam/steamapps/compatdata/883710/pfx/drive_c/windows/system32
- mf.dll -> /home/majstor/.steam/steam/steamapps/compatdata/883710/pfx/drive_c/windows/syswow64
Traceback (most recent call last):
  File "/home/majstor/python-installcab-master/installcab.py", line 305, in <module>
    process_files(output_files)
  File "/home/majstor/python-installcab-master/installcab.py", line 246, in process_files
    install_regfile(tmpdir, file_path+".reg", arch)
  File "/home/majstor/python-installcab-master/installcab.py", line 226, in install_regfile
    subprocess.call(cmd)
  File "/usr/lib64/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
mf
- amd64_microsoft-windows-mf_31bf3856ad364e35_6.1.7601.17514_none_ab34ec409a77d93c.manifest (win64)
- wow64_microsoft-windows-mf_31bf3856ad364e35_6.1.7601.17514_none_b5899692ced89b37.manifest (wow64)
mfreadwrite
- amd64_microsoft-windows-mfreadwrite_31bf3856ad364e35_6.1.7601.17514_none_177bed732ea3f85f.manifest (win64)
- wow64_microsoft-windows-mfreadwrite_31bf3856ad364e35_6.1.7601.17514_none_21d097c56304ba5a.manifest (wow64)
- mfreadwrite.dll -> /home/majstor/.steam/steam/steamapps/compatdata/883710/pfx/drive_c/windows/system32
- mfreadwrite.dll -> /home/majstor/.steam/steam/steamapps/compatdata/883710/pfx/drive_c/windows/syswow64
Traceback (most recent call last):
  File "/home/majstor/python-installcab-master/installcab.py", line 305, in <module>
    process_files(output_files)
  File "/home/majstor/python-installcab-master/installcab.py", line 246, in process_files
    install_regfile(tmpdir, file_path+".reg", arch)
  File "/home/majstor/python-installcab-master/installcab.py", line 226, in install_regfile
    subprocess.call(cmd)
  File "/usr/lib64/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
wmadmod
- amd64_microsoft-windows-wmadmod_31bf3856ad364e35_6.1.7601.17514_none_e474f0ac34979bc4.manifest (win64)
- x86_microsoft-windows-wmadmod_31bf3856ad364e35_6.1.7601.17514_none_885655287c3a2a8e.manifest (win32)
- wmadmod.dll -> /home/majstor/.steam/steam/steamapps/compatdata/883710/pfx/drive_c/windows/system32
- wmadmod.dll -> /home/majstor/.steam/steam/steamapps/compatdata/883710/pfx/drive_c/windows/syswow64
Traceback (most recent call last):
  File "/home/majstor/python-installcab-master/installcab.py", line 305, in <module>
    process_files(output_files)
  File "/home/majstor/python-installcab-master/installcab.py", line 246, in process_files
    install_regfile(tmpdir, file_path+".reg", arch)
  File "/home/majstor/python-installcab-master/installcab.py", line 226, in install_regfile
    subprocess.call(cmd)
  File "/usr/lib64/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
wmvdecod
- amd64_microsoft-windows-wmvdecod_31bf3856ad364e35_6.1.7601.17514_none_20b089c0f6efacae.manifest (win64)
- x86_microsoft-windows-wmvdecod_31bf3856ad364e35_6.1.7601.17514_none_c491ee3d3e923b78.manifest (win32)
- wmvdecod.dll -> /home/majstor/.steam/steam/steamapps/compatdata/883710/pfx/drive_c/windows/system32
- wmvdecod.dll -> /home/majstor/.steam/steam/steamapps/compatdata/883710/pfx/drive_c/windows/syswow64
Traceback (most recent call last):
  File "/home/majstor/python-installcab-master/installcab.py", line 305, in <module>
    process_files(output_files)
  File "/home/majstor/python-installcab-master/installcab.py", line 246, in process_files
    install_regfile(tmpdir, file_path+".reg", arch)
  File "/home/majstor/python-installcab-master/installcab.py", line 226, in install_regfile
    subprocess.call(cmd)
  File "/usr/lib64/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
wmadmod
- amd64_microsoft-windows-wmadmod_31bf3856ad364e35_6.1.7601.17514_none_e474f0ac34979bc4.manifest (win64)
- x86_microsoft-windows-wmadmod_31bf3856ad364e35_6.1.7601.17514_none_885655287c3a2a8e.manifest (win32)
- wmadmod.dll -> /home/majstor/.steam/steam/steamapps/compatdata/883710/pfx/drive_c/windows/system32
- wmadmod.dll -> /home/majstor/.steam/steam/steamapps/compatdata/883710/pfx/drive_c/windows/syswow64
Traceback (most recent call last):
  File "/home/majstor/python-installcab-master/installcab.py", line 305, in <module>
    process_files(output_files)
  File "/home/majstorpython-installcab-master/installcab.py", line 246, in process_files
    install_regfile(tmpdir, file_path+".reg", arch)
  File "/home/majstor/python-installcab-master/installcab.py", line 226, in install_regfile
    subprocess.call(cmd)
  File "/usr/lib64/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Done!
Now you need to get mfplat.dll version 12.0.7601.23471 from elsewhere and place it in your application directory
```
It seems to install the dlls, but after that, the game won't start.

**Comment by doitsujin** [comment]
This **still** isn't a DXVK bug.

**Comment by Ayushmaniar** [comment]
https://github.com/z0z0z/mf-installcab

Trying out the instructions in this link worked beautifully for me, please try it out and star the repository if it works for you
