### ISSUE TITLE
[macOS] Build fail since d3d10 enabled

### ISSUE THREAD

**Issue by Luke-Nukem** [doitsujin/dxvk#601]
Compiling both from the git repo as is, and using Valve Proton, the build fails when trying to change the rpath of d3d10core.dll.

```
Stripping target 'src/d3d10/d3d10core.dll'
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin/meson", line 29, in <module>
    sys.exit(mesonmain.main())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 379, in main
    return run(sys.argv[1:], launcher)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 284, in run
    return minstall.run(remaining_args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mesonbuild/minstall.py", line 466, in run
    installer.do_install(datafilename)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mesonbuild/minstall.py", line 298, in do_install
    self.install_targets(d)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mesonbuild/minstall.py", line 442, in install_targets
    install_name_mappings, verbose=False)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mesonbuild/scripts/depfixer.py", line 412, in fix_rpath
    fix_darwin(fname, new_rpath, final_path, install_name_mappings)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mesonbuild/scripts/depfixer.py", line 394, in fix_darwin
    stderr=subprocess.DEVNULL)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['install_name_tool', '/Users/luke/src/Proton/build/dxvk.win32/bin/d3d10core.dll', '-change', '@rpath/d3d11.dylib', '/Users/luke/src/Proton/build/dxvk.win32/bin/d3d11.dll']' returned non-zero exit status 1.
FAILED: meson-install 
/opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 /opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
```

**Comment by Luke-Nukem** [comment]
Trying this manually results in:

```
error: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: input file: /Users/luke/src/dxvk/test/bin/d3d10core.dll is not a Mach-O file
```

**Comment by doitsujin** [comment]
I don't support Mac OS X and I have no way to test this.

**Comment by 4ymen** [comment]
There is this if you really want to build it on your machine: https://github.com/cheald/dxvk-docker
Originally from: https://github.com/doitsujin/dxvk/pull/543

**Comment by Luke-Nukem** [comment]
@doitsujin It's kind of critical to Valve's Proton if they intend to support macOS at all. I'll continue to see if I can fix it.

**Comment by doitsujin** [comment]
If they intend to support Mac OS X, someone will have to get MoltenVK into shape and figure out how to link it to dxvk. Right now it is impossible to even use it.

**Comment by kergoth** [comment]
This looks like a meson bug in its dep fixing for macOS. They run `otool -l` to extract a list of existing rpaths, and assume that this command will fail on a binary we shouldn't be running `install_name_tool` against, but this isn't actually the case. `otool -l` will fail to extract anything but still return an exit code of 0 in this case. `llvm-objdump: '/Users/kergoth/Sandbox/Proton/build/dxvk.win32/bin/d3d10core.dll': Object is not a Mach-O file type.` is the message shown in this case, it returns 0, and then merrily tries and fails to run install_name_tool against.

meson should likely get a workaround to explicitly handle this case, or better yet, don't run mac fixers in the case where we're building with a mingw compiler as we are here. meson shouldn't try to fix up binaries with host tools when the resulting binaries aren't built for the host. I lack the knowledge of meson to say how it should really be addressed. I just hacked it in my local meson install for now.

**Comment by Luke-Nukem** [comment]
@doitsujin I'm still exploring everything that encompasses Proton - you say DXVK is actually linking to Vulkan libs?
